### ISSUE TITLE
Надо пофиксить эту дырку в центре

### ISSUE THREAD

**Issue by scandy5** [IvanDerkach/Uber-eats-IvanDerkach#21]
![image](https://user-images.githubusercontent.com/41551315/60772229-0fdf3580-a0fc-11e9-9cd1-7c04d194c16f.png)
Первое, что мне пришло в голову, то это флексы переделать на грид, но можешь сделать на свое усмотрение

**Comment by IvanDerkach** [comment]
Пока не могу решить эту проблему, если у тебя есть идеи, подскажи пожалуйста, ибо я сам не могу пока додуматься как это сделать)

**Comment by scandy5** [comment]
поменять две строчки в css 
![image](https://user-images.githubusercontent.com/41551315/61181241-3c2f1080-a62c-11e9-9245-8d5e2647e230.png)

**Comment by scandy5** [comment]
https://stackoverflow.com/questions/20626685/better-way-to-set-distance-between-flexbox-items Либо вот так
